// Copyright © 2018 Yokesh Thirumoorthi
// [This program is licensed under the "MIT License"]
// Please see the file LICENSE in the source
// distribution of this software for license terms.

// This file is typically generated by diesel.toml

table! {
    chats (id) {
        id -> Text,
        content -> Text,
    }
}
